### ISSUE TITLE
ECONNREFUSED Error

### ISSUE THREAD

**Issue by thedaftbadger** [juangranadilla/TaskBan-web#1]
Getting this error on clean install when trying to run the app....

![image](https://cloud.githubusercontent.com/assets/13657363/13053589/38bcb57e-d3fd-11e5-9be3-c2ec08312db6.png)

Changed the listed port from `8080` to `6666` but either way the same error occurs.

**Comment by juangranadilla** [comment]
It seems to be an error with the connection to the MongoDB database, but I don't know. I run this project in *Windows 10* and *Ubuntu 15.10* and it runs ok. 

Note that this is an application that I am developing for the final project for my University degree, and it could have bugs, because it's a work in progress.

Thanks for reporting this issue!
